project_id = "cedoifdkvlxuaawdmtld"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.detect-number-plate]
verify_jwt = false

[functions.send-receipt-email]
verify_jwt = false
